### PR TITLE
Add Minio as a storage option

### LINKED ISSUE #15: Using alternative S3 compatible storage?
Is it possible to use S3 alternatives like [minio](https://github.com/minio/minio) with Strata?

### PR DESCRIPTION
**Pull request by kulshekhar**
Resolves #15

### CODE REVIEW

**Comment by igorcanadi** [comment]
Thanks for your contribution!

BTW I find the directory structure a bit weird, since now we have a minio file under 'strata/cmd/mongo/lreplica_s3storage_driver' directory. Can you create a separate directory 'strata/cmd/mongo/lreplica_miniostorage_driver'? It's fine to have two binaries, at least for now.

Alternative would be to move everything into a 'strata/cmd/mongo' directory.

What do you think?

**Comment by kulshekhar** [comment]
Yes, the directory structure does look non-intuitive. One reasonable way it could be refactored is by renaming the `lreplica_s3storage_driver` to `lreplica_drivers`. This would also help avoid creating multiple binaries.

This would, however necessitate changes in the following files:

- [.gitignore](https://github.com/facebookgo/rocks-strata/blob/master/.gitignore)
- [README.md](https://github.com/facebookgo/rocks-strata/blob/master/README.md)
- [lrminiodriver.go](https://github.com/kulshekhar/rocks-strata/blob/dd929e88e9bf430007f5ab8b0baf6f1a0dc10f9f/strata/cmd/mongo/lreplica_s3storage_driver/lrminiodriver/lrminiodriver.go)
- [main.go](https://github.com/facebookgo/rocks-strata/blob/master/strata/cmd/mongo/lreplica_s3storage_driver/mongoq/main.go)
- [main.go](https://github.com/kulshekhar/rocks-strata/blob/dd929e88e9bf430007f5ab8b0baf6f1a0dc10f9f/strata/cmd/mongo/lreplica_s3storage_driver/strata/main.go)

If this refactor is acceptable, I can make these changes.

I also just noticed that I'll have to make changes in the  [main.go](https://github.com/facebookgo/rocks-strata/blob/master/strata/cmd/mongo/lreplica_s3storage_driver/mongoq/main.go) file (in `mongoq`) on the same lines as the changes made in the [main.go](https://github.com/kulshekhar/rocks-strata/blob/dd929e88e9bf430007f5ab8b0baf6f1a0dc10f9f/strata/cmd/mongo/lreplica_s3storage_driver/strata/main.go) file (in `strata`).

**Comment by igorcanadi** [comment]
> Yes, the directory structure does look non-intuitive. One reasonable way it could be refactored is by renaming the lreplica_s3storage_driver to lreplica_drivers. This would also help avoid creating multiple binaries.

Yeah this sounds good. Maybe do this in a separate PR first and then come back to this one?

> I also just noticed that I'll have to make changes in the main.go file (in mongoq) on the same lines as the changes made in the main.go file (in strata).

Refactor it out into a storage_factory.go?

**Comment by kulshekhar** [comment]
> Yeah this sounds good. Maybe do this in a separate PR first and then come back to this one?

Sounds good. I'll get on it.

> Refactor it out into a storage_factory.go?

I'm not quite sure how this will be done. I'll have to take a closer look at this.

**Comment by kulshekhar** [comment]
I've refactored the directory name in PR #17. Once that's merged, I'll make the next set of changes.

**Pull request closed without merging**
